<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>Créer un utilisateur</title>
</head>
<body>
<h1>Créer un utilisateur</h1>
<form action="/index.php?controller=user&action=store" method="POST">
    <label for="first_name">Prénom :</label>
    <input type="text" id="first_name" name="first_name" required>

    <label for="last_name">Nom :</label>
    <input type="text" id="last_name" name="last_name" required>

    <label for="email">Email :</label>
    <input type="email" id="email" name="email" required>

    <label for="password">Mot de passe :</label>
    <input type="password" id="password" name="password" required>

    <label for="confirm_password">Confirmer le mot de passe :</label>
    <input type="password" name="confirm_password" id="confirm_password" required>


    <label for="role">Rôle :</label>
    <select id="role" name="role" required>
        <option value="admin">Admin</option>
        <option value="user">User</option>
    </select>

    <button type="submit">Créer</button>
</form>
</body>
</html>
